name: trader
version: '0.1'
summary: Single-line elevator pitch for your amazing snap # 79 char long summary
description: |
    This is trader description.
confinement: devmode 
grade: devel
base: core20
parts:
  trader-service:
    plugin: npm
    source: https://github.com/xstyle/trader-service.git
    npm-node-version: 14.16.0
    build-packages:
      - npm
    override-build: |
      npm install 
      npm run-script build
      snapcraftctl build
  scripts:
    plugin: dump
    source: src/utilities    
apps:
  trader:
    command: bin/trader-service-wrapper
    daemon: simple
    environment: 
      ENV: production
    plugs:
      - network
      - network-bind